dist: focal

language: rust

sudo: required

rust:
  - nightly

cache: cargo

addons:
  apt:
    update: true
    packages:
      - cmake
      - build-essential
      - libssl-dev
      - libmysqlclient-dev

services:
  - rabbitmq

after_success: |
    if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
        `RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install --force cargo-tarpaulin`
        cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
    fi

branches:
  only:
    - master
    - develop
