[package]
name = "rabbitmq-consumer"
version = "0.6.3"
authors = ["Dario Cancelliere <dario.cancelliere@facile.it>"]
build = "build.rs"

[dependencies]
tokio = "^0.1"
tokio-current-thread = "^0.1"
tokio-process = "^0.2"
tokio-timer = "^0.2"
tokio-signal = "^0.2"
tokio-io = "^0.1"
futures = "^0.1"
lapin-futures = "^0.13"
lapin-async = "^0.13"
toml = "^0.4"
serde = "^1.0"
serde_derive = "^1.0"
diesel = { version = "^1.3", features = ["mysql", "chrono"] }
chrono = { version = "^0.4", features = ["serde"] }
env_logger = "^0.5"
base64 = "^0.9"
clap = "^2.2"
